services:
  frontend:
    build:
      context: ./FoodTok_Frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    env_file:
      - ./FoodTok_Frontend/.env
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - localstack-net
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  localstack-net:
    name: localstack-net
    driver: bridge