services:
  frontend:
    build:
      context: ./FoodTok_Frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
    ports:
      - "3000:3000"
    networks:
      - localstack-net

networks:
  localstack-net:
    name: localstack-net
    driver: bridge